## Config file

# General
period: 5 #second



# Input
spark-master: spark://xx:4000
history-server: 142.150.208.147:18080

# Parser type
# app/job/stage/task
type: app

# Metrics
app:
- x

job:
- x

stage:
- x

task:
- x


# Output
redis: 142.150.208.147:6379
